### ISSUE TITLE
Unable to install GraalVM VSCode plugin

### ISSUE THREAD

**Issue by eschulte** [hpi-swa/polyglot-live-programming#3]
Hi,

I'm able to get an older 20.2 version of GraalVM installed and activated in the GraalVM VSCode plugin.  However, when I try to install the 20.3 GraalVM and then I run the `graalvm: Set Active GraalVM Installation` command I get the following error:

```
Error running command extension.graalvm.selectGraalVMHome: Cannot read property 'JAVA_HOME' of undefined. This is likely caused by the extension that contributes extension.graalvm.selectGraalVMHome.
```

This leaves me unable to leverage the GraalVM LSP server from VSCode or to try out the features of this plugin.  Can you help me trouble shoot this installation problem?

I ran into the same problem whether installing GraalVM through the VSCode plugin, and then again after removing that install and installing GraalVM manually from the download tarball.

Thanks!

**Comment by fniephaus** [comment]
Hi @eschulte,
What version of the GraalVM extension for VS Code do you have installed? Is it `0.5.0`?

**Comment by eschulte** [comment]
Yes, `0.5.0`.

**Comment by fniephaus** [comment]
Can you set the GraalVM home in the extension's settings (Setting>Extensions>GraalVM>Home)? And what OS are you using?

**Comment by eschulte** [comment]
I'm on Mac OSx.

If I set that value under settings, then I can get a checkmark on the right GraalVM install in the "Gr" left pane.  However, if I then try to run a debug session with f5 using that GraalVM install it doesn't appear to start.  Also, if I then try to reactivate that GraalVM through the "Gr" pane by clicking the home icon I get the same error as above.

**Comment by fniephaus** [comment]
Mh this is quite hard to debug, would you have some time to jump on a call and debug this together? My email is code@fniephaus.com if you'd like to send me an invite to some video call (e.g. Zoom meeting).

**Comment by eschulte** [comment]
Will do.  Thanks!

I really enjoyed the "Example-Based Live Programming for Everyone" SPLASH presentation BTW.

**Comment by fniephaus** [comment]
Thanks a lot, @eschulte! Glad you liked our presentation! Please feel free to get in touch if you have any further questions.

Just wanted to follow up on our remote debugging session:
As it turned out, the `languageServer.inProcessServer` option needs to be turned off, so that the GraalVM extension spawns a language server by default. I've raised https://github.com/oracle/graal/issues/3041 and hope they'll clarify this and improve the default behavior. Until then, users must manually disable the option in the settings. I've updated the installation instructions accordingly via
https://github.com/hpi-swa/polyglot-live-programming/commit/c285ffe7dcd1cc3bbfb909e0e4d0fdc9bf9cef57.

**Comment by fniephaus** [comment]
One more thing:
I can reproduce the original error (*Cannot read property 'JAVA_HOME' of undefined*) and it looks like the problem is in GraalVM's extension (see https://github.com/oracle/graal/issues/3040).
